[build]
  command = "chmod +x mvnw && ./mvnw clean install && java -jar target/calendrier-spring.jar"
  publish = "target/calendrier-spring.jar"

[[redirects]]
  from = "/*"
  to = "/index"
  status = 200
